### ISSUE TITLE
Keep narrow display from side scrolling comments

### ISSUE THREAD

**Issue by otrajman** [asah/zulip#6]
Remove "width: 100%" from the message_content class so it can reflow within the container will keep narrow displays from side scrolling on long URLs.

**Comment by asah** [comment]
can you point me a little more specifically?
```
$ find . -name "*.css" | xargs grep -Hn message_content
./static/styles/drafts.css:103:        .message_content {
./static/styles/dark_theme.css:352:    div.message_content thead,
./static/styles/compose.css:173:    .message_content {
./static/styles/zulip.css:797:    .message_content:not(:empty) {
./static/styles/zulip.css:1481:.message_content {
./static/styles/zulip.css:1653:    /* to match .message_content */
./static/styles/zulip.css:3082:    .message_content {
```

**Comment by otrajman** [comment]
I'm stymied. The chrome inspector links to zulip.css:1489 which includes the following snippet (the width is set in the @meda condition). That's not the raw source thought, so I'm not sure where in the compile process it gets introduced. It may be a boostrap flag, which I'm not familiar with.

.message_content {
    line-height: 1.214;
    min-height: 50px;
    margin-left: 46px;
    display: block;
    position: relative;
    overflow: hidden;
    @media (width < $sm_min) {
	width: 100%;
    }
    @media (width >= $sm_min) {
	width: 105%;
    }

**Comment by asah** [comment]
no worries this is perfect - I can dig in... the right way to do this is
probably via js (jquery).

**Comment by asah** [comment]
sent you a PM we can use to test :-)

I've got the overflow / side scroll reproducing on my desktop:

<img width="458" alt="image" src="https://user-images.githubusercontent.com/140002/153469183-cee86fc2-1f88-40eb-9aac-b049a281dee8.png">

<img width="439" alt="image" src="https://user-images.githubusercontent.com/140002/153469294-5c3d5a62-fcbc-4236-a122-c0ca3f391d2e.png">

**Comment by asah** [comment]
and I see the same inspector width: 100% you do, and removing it seems to fix the problem for me as well:

<img width="337" alt="image" src="https://user-images.githubusercontent.com/140002/153469466-60fe140a-2830-4e7a-a8e2-60e1f8ba09e6.png">

**Comment by asah** [comment]
and here's the zulip.css code, which comes from [here](https://github.com/asah/zulip/blob/forecast.chat/static/styles/zulip.css#L1481) - my bad, I forgot to mention that I'm working on the forecast.chat branch !

<img width="251" alt="image" src="https://user-images.githubusercontent.com/140002/153469584-370001b0-5153-4cb3-ba51-17af2c3f923d.png">

**Comment by asah** [comment]
confirmed fixed on my phone... how's it look for you?
